<a href="https://colab.research.google.com/github/brandonliu12/deep-learning-challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [66]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [67]:
application_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [68]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [69]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [70]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [71]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 100

# Create a list of application types to be replaced
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check if binning was successful
print(application_df['APPLICATION_TYPE'].value_counts())

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [72]:
# Look at CLASSIFICATION value counts for binning
classification_type_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_type_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [73]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_type_counts_filtered = classification_type_counts[classification_type_counts > 1]
print(classification_type_counts_filtered)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [74]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [75]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, columns=['AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'APPLICATION_TYPE'])

# Check the updated DataFrame
application_df.head()

,IS_SUCCESSFUL,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C1270,...,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,APPLICATION_TYPE_T9
0,1,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [76]:
application_df.columns

Index(['IS_SUCCESSFUL', 'AFFILIATION_CompanySponsored',
       'AFFILIATION_Family/Parent', 'AFFILIATION_Independent',
       'AFFILIATION_National', 'AFFILIATION_Other', 'AFFILIATION_Regional',
       'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200', 'CLASSIFICATION_C1270',
       ...
       'APPLICATION_TYPE_Other', 'APPLICATION_TYPE_T10',
       'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3', 'APPLICATION_TYPE_T4',
       'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6', 'APPLICATION_TYPE_T7',
       'APPLICATION_TYPE_T8', 'APPLICATION_TYPE_T9'],
      dtype='object', length=8798)

In [77]:
from sklearn.model_selection import train_test_split

# Separate features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1)
y = application_df['IS_SUCCESSFUL']

# Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [78]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [87]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the deep learning model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=X_train_scaled.shape[1]))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
858/858 [==============================] - 6s 5ms/step - loss: 0.6127 - accuracy: 0.6808
Epoch 2/100
858/858 [==============================] - 5s 6ms/step - loss: 0.4519 - accuracy: 0.7905
Epoch 3/100
858/858 [==============================] - 4s 5ms/step - loss: 0.4049 - accuracy: 0.8097
Epoch 4/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3996 - accuracy: 0.8094
Epoch 5/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3978 - accuracy: 0.8105
Epoch 6/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3965 - accuracy: 0.8110
Epoch 7/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3955 - accuracy: 0.8112
Epoch 8/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3955 - accuracy: 0.8121
Epoch 9/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3950 - accuracy: 0.8118
Epoch 10/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3945 - accuracy: 0.8103
Epoch 11/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3938 - accuracy: 0.8127
Epoch 12/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3936 - accuracy: 0.8125
Epoch 13/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3926 - accuracy: 0.8128
Epoch 14/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3933 - accuracy: 0.8126
Epoch 15/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3922 - accuracy: 0.8125
Epoch 16/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3920 - accuracy: 0.8132
Epoch 17/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3919 - accuracy: 0.8128
Epoch 18/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3914 - accuracy: 0.8134
Epoch 19/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3909 - accuracy: 0.8129
Epoch 20/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3909 - accuracy: 0.8137
Epoch 21/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3908 - accuracy: 0.8144
Epoch 22/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3907 - accuracy: 0.8133
Epoch 23/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3900 - accuracy: 0.8127
Epoch 24/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3903 - accuracy: 0.8142
Epoch 25/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3897 - accuracy: 0.8136
Epoch 26/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3897 - accuracy: 0.8146
Epoch 27/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3896 - accuracy: 0.8139
Epoch 28/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3898 - accuracy: 0.8148
Epoch 29/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3894 - accuracy: 0.8144
Epoch 30/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3891 - accuracy: 0.8132
Epoch 31/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3889 - accuracy: 0.8147
Epoch 32/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3887 - accuracy: 0.8143
Epoch 33/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3889 - accuracy: 0.8141
Epoch 34/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3886 - accuracy: 0.8151
Epoch 35/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3883 - accuracy: 0.8150
Epoch 36/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3886 - accuracy: 0.8150
Epoch 37/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3880 - accuracy: 0.8150
Epoch 38/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3882 - accuracy: 0.8152
Epoch 39/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3880 - accuracy: 0.8151
Epoch 40/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3883 - accuracy: 0.8150
Epoch 41/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3881 - accuracy: 0.8160
Epoch 42/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3878 - accuracy: 0.8156
Epoch 43/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3874 - accuracy: 0.8149
Epoch 44/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3872 - accuracy: 0.8173
Epoch 45/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3874 - accuracy: 0.8145
Epoch 46/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3871 - accuracy: 0.8162
Epoch 47/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3871 - accuracy: 0.8156
Epoch 48/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3869 - accuracy: 0.8156
Epoch 49/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3870 - accuracy: 0.8160
Epoch 50/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3871 - accuracy: 0.8158
Epoch 51/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3869 - accuracy: 0.8161
Epoch 52/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3863 - accuracy: 0.8152
Epoch 53/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3866 - accuracy: 0.8154
Epoch 54/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3866 - accuracy: 0.8158
Epoch 55/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3864 - accuracy: 0.8161
Epoch 56/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3865 - accuracy: 0.8160
Epoch 57/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3866 - accuracy: 0.8156
Epoch 58/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3863 - accuracy: 0.8154
Epoch 59/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3863 - accuracy: 0.8151
Epoch 60/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3867 - accuracy: 0.8153
Epoch 61/100
858/858 [==============================] - 5s 5ms/step - loss: 0.3862 - accuracy: 0.8161
Epoch 62/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3863 - accuracy: 0.8167
Epoch 63/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3863 - accuracy: 0.8162
Epoch 64/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3864 - accuracy: 0.8152
Epoch 65/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3858 - accuracy: 0.8153
Epoch 66/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3861 - accuracy: 0.8150
Epoch 67/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3860 - accuracy: 0.8164
Epoch 68/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3858 - accuracy: 0.8157
Epoch 69/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3862 - accuracy: 0.8169
Epoch 70/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3861 - accuracy: 0.8158
Epoch 71/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3854 - accuracy: 0.8153
Epoch 72/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3856 - accuracy: 0.8157
Epoch 73/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3856 - accuracy: 0.8164
Epoch 74/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3855 - accuracy: 0.8159
Epoch 75/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3855 - accuracy: 0.8161
Epoch 76/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3852 - accuracy: 0.8165
Epoch 77/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3855 - accuracy: 0.8159
Epoch 78/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3858 - accuracy: 0.8168
Epoch 79/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3855 - accuracy: 0.8158
Epoch 80/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3854 - accuracy: 0.8168
Epoch 81/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3853 - accuracy: 0.8159
Epoch 82/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3854 - accuracy: 0.8158
Epoch 83/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3851 - accuracy: 0.8163
Epoch 84/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3853 - accuracy: 0.8162
Epoch 85/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3849 - accuracy: 0.8168
Epoch 86/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3854 - accuracy: 0.8166
Epoch 87/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3857 - accuracy: 0.8154
Epoch 88/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3851 - accuracy: 0.8161
Epoch 89/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3851 - accuracy: 0.8160
Epoch 90/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3854 - accuracy: 0.8158
Epoch 91/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3852 - accuracy: 0.8161
Epoch 92/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3851 - accuracy: 0.8171
Epoch 93/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3848 - accuracy: 0.8162
Epoch 94/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3850 - accuracy: 0.8160
Epoch 95/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3849 - accuracy: 0.8151
Epoch 96/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3848 - accuracy: 0.8165
Epoch 97/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3846 - accuracy: 0.8164
Epoch 98/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3851 - accuracy: 0.8161
Epoch 99/100
858/858 [==============================] - 4s 5ms/step - loss: 0.3845 - accuracy: 0.8166
Epoch 100/100
858/858 [==============================] - 5s 6ms/step - loss: 0.3845 - accuracy: 0.8170
215/215 - 0s - loss: 0.6943 - accuracy: 0.7153 - 495ms/epoch - 2ms/step
Loss: 0.6943193078041077, Accuracy: 0.7153061032295227

In [88]:
# Export our model to HDF5 file
nn_model.save("my_model.h5")